#! /bin/bash
#
# swapcase 1.0.1, 2020-10-04
#
# Invertiert die Groß- und Kleinschreibung, jeder Kleinbuchstabe wird
# durch den entsprechenden Großbuchstaben ersetzt -- und umgekehrt.
#
# Bernd Storck, https://www.facebook.com/BStLinux/
#

newStr=
loopEnd="$(( ${#1} - 1 ))"
( LANG="de_DE.UTF-8" 
for i in $(seq 0 "$loopEnd"); do
    oldChar="${1:$i:1}"   ## der einzelne Buchstabe
    if grep -c '[a-zäöüß]' <<< "$oldChar" &> /dev/null; then  	## Wenn es ein Kleinbuchstabe ist…
		if [ "$oldChar" != "ß" ]; then
			newStr+="$( tr '[a-zäöü]' '[A-ZÄÖÜ]' <<< "$oldChar" )"
		else
			newStr+="$( sed -E 's/ß/SS/' <<< "$oldChar" )"
		fi
	else							## Wenn es ein Grossbuchstabe ist…
		newStr+="$( tr '[A-ZÄÖÜ]' '[a-zäöü]' <<< "$oldChar" )"
	fi
done 

echo "$newStr" )
